{% set name = "cyberpunk-theme" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cyberpunk-theme-{{ version }}.tar.gz
  sha256: 96d39399002399642894180dd4364477911aa84a72910e674b33b8188053cd4d

build:
  entry_points:
    - cyberpunk-theme = cyberpunk_theme.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tkstyle

test:
  imports:
    - cyberpunk_theme
  commands:
    - pip check
    - cyberpunk-theme
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/cyberpunk-theme
  summary: Dark theme for Python desktop apps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
